import Nav from "./components/Nav";
import "./globals.css";
import { Martian_Mono, Playwrite_AU_SA, Righteous } from "next/font/google";

const martian = Martian_Mono({
  subsets: ["latin"],
  variable: "--font-martian",
});

const playwrite = Playwrite_AU_SA({
  subsets: ["latin"],
  variable: "--font-playwrite",
});

const righteous = Righteous({
  subsets: ["latin"],
  variable: "--font-righteous",
  weight: "400",
});

export const metadata = {
  title: "Deepak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${martian.variable} ${playwrite.variable} ${righteous.variable}`}
    >
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@100..800&family=Playwrite+AU+SA:wght@100..400&family=Righteous&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-[#f1faee]">
        <Nav />
        {children}
      </body>
    </html>
  );
}
